apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginxwebdav.fullname" . }}-{{ .Values.persistence.name }}
  annotations:
  {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nginxwebdav" . | nindent 4 }}
  {{- with .Values.persistence.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}